#!/usr/bin/env bash
set -euo pipefail
shopt -s lastpipe

which awk md5sum jo jq > /dev/null

realpath "$0" | read -r UNIPLAY
dirname "$UNIPLAY" | read -r SCRIPT_DIR
UNIPLAYDIRS=(\
    "$XDG_CONFIG_HOME/uniplay/fetchers" \
    "$XDG_CONFIG_HOME/uniplay/fetchers" \
    "$XDG_CONFIG_HOME/uniplay/utilities" \
    "$SCRIPT_DIR/../share/uniplay/fetchers" \
    "$SCRIPT_DIR/../share/uniplay/fetchers" \
    "$SCRIPT_DIR/../share/uniplay/utilities" \
    "$SCRIPT_DIR/fetchers" \
    "$SCRIPT_DIR/fetchers" \
    "$SCRIPT_DIR/utilities" \
)
printf -v UNIPLAYPATH "%s:" "${UNIPLAYDIRS[@]}"
UNIPLAYPATH="${UNIPLAYPATH%:}"

export UNIPLAY UNIPLAYPATH

if [[ "$#" -eq 0 ]]; then
    echo "uniplay: First argument should be a fetcher" >&2
    exit 1
fi

NAME="$1"
shift 1

if [[ "$#" -eq 0 ]]; then
    mapfile JSON
else
    if [[ -r "$1" ]]; then
        jo file="$1"
    else
        jo url="$1"
    fi | mapfile JSON
fi

if ! PATH="$PATH:$UNIPLAYPATH" command -v "$NAME.sh" | read -r FETCHER; then
    <<< "$NAME" md5sum \
        | cut -c -32 \
        | read -r HASH

    if ! PATH="$PATH:$UNIPLAYPATH" command -v "$HASH.sh" | read -r FETCHER; then
        echo "uniplay: Cannot find $NAME: ${JSON[@]}" >&2
        exit 2
    fi
fi

<<< "${JSON[@]}" jq --arg uni "$UNIPLAY" '.uniplay=$uni' \
    | "$FETCHER"

if <<< "${JSON[@]}" jq -r '.delete // empty' | read -r TMPFILE; then
    echo "uniplay: Delete temporary $TMPFILE" >&2
    rm -r "$TMPFILE"
fi
