#!/usr/bin/env bash
set -e

which jo > /dev/null

read -r UNI < <(realpath "$0")
read -r UNI_DIR < <(dirname "$UNI")

read -r HASH < <(md5sum <<< "$1" | cut -c -32)
POSSIBLE_FETCHERS=(\
    "$UNI_DIR/fetchers/$1.sh" \
    "$UNI_DIR/fetchers/$HASH.sh" \
    "$XDG_CONFIG_HOME/uniplayer/fetchers/$1.sh" \
    "$XDG_CONFIG_HOME/uniplayer/fetchers/$HASH.sh" \
)

FETCHER=
for CHECK_FETCHER in "${POSSIBLE_FETCHERS[@]}"; do
    if [[ -e "$CHECK_FETCHER" ]]; then
        FETCHER="$CHECK_FETCHER"
        break
    fi
done
if [[ ! -e "$FETCHER" ]]; then
    echo "Cannot find $1" >&2
    exit 1
fi

export UNI
if [[ -n "$2" ]]; then
    "$FETCHER" < <(jo url="$2" uni="$UNI")
else
    "$FETCHER"
fi
