#!/usr/bin/env bash
set -e
shopt -s lastpipe

which awk md5sum jo jq cut xargs > /dev/null

realpath "$0" | read -r UNIPLAY
dirname "$UNIPLAY" | read -r SCRIPT_DIR
export UNIPLAY

if [[ "$1" == -f ]]; then
    NAME="$2"
    URL="$3"
elif [[ -z "$1" || "$1" =~ [^:]+:// ]]; then
    if [[ -z "$1" ]]; then
        jq -r .item | read -r URL
    else
        URL="$1"
    fi

    [[ "$URL" =~ ([^:]+)://([^/]+) ]]
    if [[ "${BASH_REMATCH[1]:0:4}" == http ]]; then
        DOMAIN="${BASH_REMATCH[2]}"
    else
        DOMAIN="${BASH_REMATCH[1]}"
    fi

    awk -F. '{print $(NF-1)}' <<< "$DOMAIN" | read -r NAME
elif [[ "$1" =~ \.ulst$ ]]; then
    "$UNIPLAY" -f ulst "$1" | "$UNIPLAY"
    exit 0
else
    echo "uniplay: Unexpected arguments or input" >&2
    exit 2
fi

md5sum <<< "$NAME" | cut -c -32 | read -r HASH
POSSIBLE_FETCHERS=(\
    "$SCRIPT_DIR/fetchers/$NAME.sh" \
    "$SCRIPT_DIR/fetchers/$HASH.sh" \
    "$XDG_CONFIG_HOME/uniplay/fetchers/$NAME.sh" \
    "$XDG_CONFIG_HOME/uniplay/fetchers/$HASH.sh" \
)

FETCHER=
for CHECK_FETCHER in "${POSSIBLE_FETCHERS[@]}"; do
    if [[ -e "$CHECK_FETCHER" ]]; then
        FETCHER="$CHECK_FETCHER"
        break
    fi
done
if [[ ! -e "$FETCHER" ]]; then
    echo "uniplay: Cannot find $NAME" >&2
    exit 3
fi

if [[ -n "$URL" ]]; then
    jo result=url item="$URL" uniplay="$UNIPLAY" | "$FETCHER"
else
    "$FETCHER"
fi
