#!/usr/bin/env bash
set -e

which awk md5sum > /dev/null

read -r UNIPLAYER < <(realpath "$0")
read -r SCRIPT_DIR < <(dirname "$UNIPLAYER")
UNI="$SCRIPT_DIR/uni"

URL="$1"
if [[ "$URL" =~ https?:// ]]; then
    read -r DOMAIN < <(awk -F/ '{print $3}' <<< "$URL")
    read -r ONLYHOST < <(awk -F. '{print $(NF-1)}' <<< "$DOMAIN")
    read -r HOSTHASH < <(md5sum <<< "$ONLYHOST" | cut -c -32)

    case "$HOSTHASH" in
        c015fff88070de99d94611d6da69b934) "$UNI" c015fff88070de99d94611d6da69b934 "$URL";;
        3451cf94720cf02db675405dafbbee07) "$UNI" 3451cf94720cf02db675405dafbbee07 "$URL";;
        *) echo "Unimplemented fetcher for $URL" >&2 && exit 1;;
    esac
else
    if [[ "$1" =~ \.ulst$ ]]; then
        read -r URL < <("$UNI" ulst "$URL" | jq -r .url)
        "$UNIPLAYER" "$URL"
    else
        echo "Unimplemented fetcher for $URL" >&2 && exit 2
    fi
fi
