#!/usr/bin/env bash
set -e

which awk md5sum jo jq cut xargs > /dev/null

read -r UNIPLAY < <(realpath "$0")
read -r SCRIPT_DIR < <(dirname "$UNIPLAY")
export UNIPLAY

if [[ "$1" == -f ]]; then
    NAME="$2"
    URL="$3"
elif [[ "$1" =~ https?:// ]]; then
    read -r DOMAIN < <(awk -F/ '{print $3}' <<< "$1")
    read -r NAME < <(awk -F. '{print $(NF-1)}' <<< "$DOMAIN")
    URL="$1"
elif [[ "$1" =~ \.ulst$ ]]; then
    exec "$UNIPLAY" -f ulst "$1" | "$UNIPLAY"
else
    exec jq -r .url | xargs -o "$UNIPLAY"
fi

read -r HASH < <(md5sum <<< "$NAME" | cut -c -32)
POSSIBLE_FETCHERS=(\
    "$SCRIPT_DIR/fetchers/$NAME.sh" \
    "$SCRIPT_DIR/fetchers/$HASH.sh" \
    "$XDG_CONFIG_HOME/uniplay/fetchers/$NAME.sh" \
    "$XDG_CONFIG_HOME/uniplay/fetchers/$HASH.sh" \
)

FETCHER=
for CHECK_FETCHER in "${POSSIBLE_FETCHERS[@]}"; do
    if [[ -e "$CHECK_FETCHER" ]]; then
        FETCHER="$CHECK_FETCHER"
        break
    fi
done
if [[ ! -e "$FETCHER" ]]; then
    echo "Cannot find $NAME" >&2
    exit 1
fi

if [[ -n "$URL" ]]; then
    "$FETCHER" < <(jo result="url" url="$URL" uniplay="$UNIPLAY")
else
    "$FETCHER"
fi
